todo_app/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('new/', views.TodoNew, name='new'),
    path('created/', views.TodoCreated),
    path('list/', views.TodoListView.as_view()),
    path('single/', views.TodoSingleView.as_view(), name='single'),
    path('delete_get/<int:todo_id>/', views.TodoDeleteView, name='delete_get'),
    path('delete_post/',views.TodoDeleteViewPost),
    path('update_checks/', views.TodoUpdateChecks),
]

todo_app/todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo_app/todo/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=128)
    created = models.DateTimeField()
    checked = models.BooleanField()

    def __str__(self):
        return self.title

todo_app/todo/forms.py
from django import forms

class TodoNewForm(forms.Form):
  title = forms.CharField(max_length=128)

todo_app/todo/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from . import forms, models


def TodoNew(request):
  todoNewForm = forms.TodoNewForm()
  
  context = {
    'form_new': todoNewForm
  }
  
  return render(request, 'todo-new.html', context)


####################################################

def TodoCreated(request):
  todoNewForm = forms.TodoNewForm(request.POST)

  title = todoNewForm['title'].value()
  created = datetime.now()

  context = {
    'title': title
  }

  todo = models.Todo(title=title, created=created, checked=False)
  todo.save()

  return render(request, 'todo-created.html', context)

####################################################

class TodoListView(TemplateView):
  template_name = 'todo-list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)

      todos = models.Todo.objects.all()
      context['todos'] = todos

      return context


####################################################

class TodoSingleView(FormView):
  template_name = 'todo-single.html'
  form_class = forms.TodoNewForm
  success_url = '/todo/single'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['todos'] = models.Todo.objects.all()
      return context

  def form_valid(self, form):
      title = form['title'].value()
      created = datetime.now()

      todo = models.Todo(title=title, created=created, checked=False)
      todo.save()

      return self.render_to_response(self.get_context_data())


def TodoDeleteView(request, todo_id):
    todo = models.Todo.objects.filter(id=todo_id)
    todo.delete()
    return redirect('/todo/single/')

def TodoDeleteViewPost(request):
    print(request.POST)
    return redirect('/todo/single/')


def TodoUpdateChecks(request):
    pairs = request.POST.getlist('todo_check')
    
    for pair in pairs:
      tid, val = pair.split(':')

      tid = int(tid)
      val = val == 'True'

      todo = models.Todo.objects.get(id=tid)
      todo.checked = val
      todo.save()
     
    return redirect('/todo/single/')

todo_app/todo/templates/todo-created.html
<html>
<body>
    <div>
        Creado el todo: {{ title }}
    </div>
<br>

<a href="{% url 'todo:new' %}"  class="back">Retornar</a>

</body>
</html>

todo_app/todo/templates/todo-list.html
<html>
<body>
  <a href="{% url 'todo:new' %}">New</a>
  <hr>
  <ul>
  {% for todo in todos %}
    <li>{{ todo.title }}</li>
  {% endfor %}
  </ul>
</body>
</html>

todo_app/todo/templates/todo-new.html
<html>
<body>
  <a href="/todo/list/">Lista</a>
  <hr>

  Crear nuevo todo item 
  <form method="post" action="/todo/created/">
    {% csrf_token %}

    {{ form_new }}

    <input type="submit">
  </form>
</body>
</html>

todo_app/todo/templates/todo-single.html
<html>
<head>
<style>
.delete-link {
  color: red;
  cursor: pointer;
  text-decoration: none;
}
</style>
<script>

function UpdateHidden(checkbox, todoId) {
  let hidden_input = checkbox.nextElementSibling;
  let text = checkbox.checked ? 'True' : 'False';
  hidden_input.value = `${todoId}:${text}`;
}

</script> 
</head>
<body>
  {% if todos %}
    <form method="post" action="/todo/update_checks/">
      {% csrf_token %}
      Todos:
      <ul>
      {% for todo in todos %}
        <li>
          <input type="checkbox" id="check" onchange="UpdateHidden(this, '{{ todo.id }}')" {% if todo.checked %} checked{% endif %}>
          <input type="hidden" name="todo_check" value="{{ todo.id }}:{{ todo.checked }}">
          <span>{{ todo.title }}</span>
          <a class="delete-link" href="{% url 'todo:delete_get' todo.id %}">X</a>
        </li>
      {% endfor %}
      </ul>
      <button type="submit">Actualizar</button>
    </form>
    Todos:
    <ul>
      {% for todo in todos %}
      <li>
        <span>{{ todo.title }}</span>
        <form method="post" action="/todo/delete_post/">
          {% csrf_token %}
          <input name="prueba" type="hidden" value="{{ todo.id }}">
          <button type="submit">Eliminar</button>
        </form>
      </li>
      {% endfor %}
    </ul>

  {% else %}
    Sin TODOs
  {% endif %}
  <hr>
  Agregar
  <form method="post" action="{% url 'todo:single' %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
</body>
</html>